edu/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'edu'

urlpatterns = [
    path('', views.EduListView.as_view(), name='edu_list'),
    path('study_list/', views.StudyListView.as_view(), name='study_list'),
    # path('pdf', views.pdf_view, name='pdf'),
    path('write/', views.edu_write_view, name='edu_write'),
    path('<int:pk>/', views.edu_detail_view, name='edu_detail'),
    path('<int:pk>/edit/', views.edu_edit_view, name='edu_edit'),
    path('<int:pk>/delete/', views.edu_delete_view, name='edu_delete'),
    path('<int:pk>/savetime/', views.saveTime, name='edu_save'),
    path('download/<int:pk>', views.edu_download_view, name="edu_download"),

    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

exam/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'exam'

urlpatterns = [
    path('test/', views.exam_test_view, name='exam_test'),


    path('', views.ExamListView.as_view(), name='exam_list'),
    path('<int:pk>/', views.exam_detail_view, name='exam_detail'),

    path('write/', views.exam_write_view, name='exam_write'),
    path('quiz/', views.quiz_write_view, name='quiz_write'),
    path('<int:pk>/edit/', views.question_write_view, name='question_write'),
    path('<int:pk>/submit/', views.exam_submit_view, name='exam_submit'),




]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zzz/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('edu/', include('edu.urls')),
    path('cert/', include('cert.urls')),
    path('exam/', include('exam.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

edu/models.py
import os
from django.db import models
from django.conf import settings
from django.db.models.deletion import SET_NULL
from django.utils import timezone
from uuid import uuid4
from datetime import datetime


from users.choice import *
"""
교육
날짜
카테고리
제목
내용
동영상
"""

def get_file_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    return ''.join(['upload_file/edu/', ymd_path, uuid_name])

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name='상품명')
    description = models.TextField(blank=True, verbose_name='설명')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=128)
    price = models.IntegerField()
    upload_files = models.FileField(upload_to='product/', null=True, blank=True, verbose_name='파일')
    image = models.ImageField(upload_to="product/", null=True, blank=True, verbose_name='이미지')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    updated_date = models.DateTimeField(auto_now=True, verbose_name="업데이트")


    class Meta:
        ordering = ('name', )
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self) -> str:
        return f'{self.name}'


    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Product, self).delete(*args, **kargs)

    


class Videos(models.Model):
    title = models.CharField(max_length=100)
    video = models.FileField(upload_to='videos/')
        
    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name = 'video'
        verbose_name_plural = 'videos'

exam/models.py
from django.db import models
from django.db.models.fields import CharField
from users.choice import *
from django.conf import settings
from django.db.models.deletion import SET_NULL
from edu.models import Product

# Create your models here.

class QuizContents(models.Model):
    quiz_title = models.CharField(max_length=128, null=False, verbose_name="quiz_title")
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=128, verbose_name="분류")
    cert = models.BooleanField(default=False, verbose_name="수료여부")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='상품명', default='')
    num_exam = models.IntegerField(default=3, verbose_name="응시기회") 
    study_cert = models.BooleanField(default=False, verbose_name="응시조건여부")
    def __str__(self):
        return self.quiz_title

    class Meta:
        db_table = 'QuizContents'
        verbose_name = 'QuizContents'
        verbose_name_plural = 'QuizContents'
        ordering = ["quiz_title"]

class Quiz(models.Model):
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=128, verbose_name="분류", null=True)
    quiz_title = models.ForeignKey(QuizContents, on_delete=models.CASCADE, verbose_name="quiz_title")
    question = models.CharField(max_length=200,null=True)
    op1 = models.CharField(max_length=200,null=True)
    op2 = models.CharField(max_length=200,null=True)
    op3 = models.CharField(max_length=200,null=True)
    op4 = models.CharField(max_length=200,null=True)
    op5 = models.CharField(max_length=200,null=True)
    ans = models.CharField(max_length=200,null=True)
    
    def __str__(self):
        return f'{self.quiz_title}'
    
    class Meta:
        db_table = 'Quiz'
        verbose_name = 'Quiz'
        verbose_name_plural = 'Quiz'
        ordering = ["quiz_title"]

exam/forms.py
from django import forms
from .models import QuizContents, Quiz

class addExamForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(addExamForm, self).__init__(*args, **kwargs)
        self.fields['quiz_title'].label = '제목'
        self.fields['quiz_title'].widget.attrs.update({
            'placeholder': '제목을 입력해주세요.',
            'class': 'form-control',
            'id': 'form_title',
            'autofocus': True,
        })
        self.fields['category'].label = '분류'
        self.fields['category'].widget.attrs.update({
            'placeholder': '분류를 입력해주세요.',
            'autofocus': True,
        })

        self.fields['product'].label = '교육'
        self.fields['product'].widget.attrs.update({
            'placeholder': '교육을 입력해주세요.',
            'autofocus': True,
        })
    class Meta:
        model = QuizContents
        fields = ['quiz_title', 'category', 'product']

class addQuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields="__all__"

exam/views.py
from django.db.models.query import prefetch_related_objects
from django.forms.widgets import PasswordInput
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.generic import View, ListView
from django.template.loader import get_template, render_to_string
from django.db.models import Q

from datetime import datetime, timedelta
import exam
from users.decorators import * 
from .forms import *
from .models import Quiz, QuizContents
from payment.models import PurchasedItem
from django.shortcuts import render, get_object_or_404, redirect

import json

class ExamListView(ListView):
    model = QuizContents
    bought_items = PurchasedItem
    paginate_by = 10
    template_name = 'exam/exam_list.html'
    context_object_name = 'exam_list' 

    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        exam_list = []
        try:
            study_list = PurchasedItem.objects.filter(user=self.request.user)
            for item in study_list:
                print(item.product)
                studied_time = item.total_time
                try:
                    (h, m, s) = studied_time.split(':')
                    time = timedelta(hours=int(h), minutes=int(m), seconds=int(s))
                except:
                    time = timedelta(hours=int(0), minutes=int(0), seconds=int(0))

                if time > timedelta(hours=int(0), minutes=int(20), seconds=int(0)):
                    exam_item = QuizContents.objects.get(product=item.product)
                    exam_item.study_cert = True
                    if item.certificated == True:
                        exam_item.cert = True
                else:
                    exam_item = QuizContents.objects.get(product=item.product)
                    exam_item.study_cert = False

                exam_list.append(exam_item)
        except:
            pass

        if search_keyword :
            if len(search_keyword) > 1 :
                if search_type == 'all':
                    search_notice_list = exam_list.filter(Q (quiz_title__icontains=search_keyword) | Q (category__icontains=search_keyword))
                elif search_type == 'title':
                    search_notice_list = exam_list.filter(quiz_title_icontains=search_keyword)    
                elif search_type == 'catagory':
                    search_notice_list = exam_list.filter(category__icontains=search_keyword)    
                return search_notice_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return exam_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1 :
            context['q'] = search_keyword
        context['type'] = search_type

        return context



# 시험등록
@login_message_required
@admin_required
def exam_write_view(request):
    if request.method == "POST":
        QuizContentForm = addExamForm(request.POST)
        if QuizContentForm.is_valid():
            exam = QuizContentForm.save(commit = False)
            exam.save()
            return redirect('exam:exam_list')
    else:
        QuizContentForm = addExamForm()
    return render(request, "exam/exam_write.html", {'QuizContentForm': QuizContentForm})

# 퀴즈등록
@login_message_required
@admin_required
def quiz_write_view(request):
    if request.method == "POST":
        QuizForm = addQuizForm(request.POST)
        print(QuizForm.is_valid())
        if QuizForm.is_valid():
            quiz = QuizForm.save(commit = False)
            quiz.save()
            return redirect('exam:exam_list')
    else:
        QuizForm = addQuizForm()
    return render(request, "exam/quiz_write.html", {'QuizForm':QuizForm})


@login_message_required
@admin_required
def question_write_view(request, pk):
    exam = QuizContents.objects.get(id=pk)
    
    if request.method == "POST":
        if(exam.writer == request.user or request.user.level == '0'):
            form = addExamForm(request.POST, instance=exam)
            if form.is_valid():
                exam = form.save(commit = False)
                exam.save()
                messages.success(request, "수정되었습니다.")
                return redirect('/exam/'+str(pk))
    else:
        exam = QuizContents.objects.get(id=pk)
        if request.user.level == '0':
            form = addExamForm(instance=exam)
            context = {
                'form': form,
                'edit': '수정하기',
            }
            return render(request, "exam/exam_write.html", context)
        else:
            messages.error(request, "본인 게시글이 아닙니다.")
            return redirect('/exam/'+str(pk))

@login_message_required
def exam_test_view(request):
    return render(request, 'exam/test.html')

@login_message_required
def exam_submit_view(request, name):
    exam = get_object_or_404(QuizContents, name=name)
    title = exam
    quizs = Quiz.objects.filter(quiz_title=title)

    context = {
        'exam': exam,
        'quiz_list':quizs,
        'passed':'',
    }
    return render(request, 'exam/exam_detail.html', context)



@login_message_required
def exam_detail_view(request, pk):
    print(request.session)
    exam = get_object_or_404(QuizContents, product_id=pk)
    exam.num_exam -= 1
    exam.save()
    title = exam
    quizs = Quiz.objects.filter(quiz_title=title)

    context = {
        'exam': exam,
        'quiz_list':quizs,
    }
    return render(request, 'exam/exam_detail.html', context)


@login_message_required
def exam_submit_view(request, pk):
    users_ans = json.loads(request.body,  encoding="UTF-8")
    score = 0
    real_ans = {}
    exam = QuizContents.objects.get(product_id=pk)
    title = exam
    quizs = Quiz.objects.filter(quiz_title=title)
    certificated = False

    for quiz in quizs:
        real_ans[str(quiz.id)] = quiz.ans
    print(real_ans)
    print(users_ans)

    for question, answer in real_ans.items():
        if users_ans[question] == answer:
            score += 20

    purchaseds = PurchasedItem.objects.filter(user=request.user)
    for item in purchaseds:
        if item.product.id == pk:
            if item.certificated == False:
                if score >= 60:
                    print('cert')
                    certificated = True
                    item.certificated = certificated
                    item.save()
                else:
                    print('Failed')
                    certificated = False
    context = {
        'score' : score,
        'certificated' : certificated,
    }
    return HttpResponse(json.dumps(context), content_type="application/json")

templates/exam/exam_list.html
{% extends "users/main_base.html" %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}

<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">시험</h4>
            {% if q %}
            <h5 style="color: gray; font-weight: 550;"><i class="fas fa-search"></i>&nbsp;'{{ q }}' 검색 결과입니다.</h5>
            {% endif %}
        </div>
    </div>
    <div>
        <table class="table table-sm table-hover">
            <thead style="border-top: 1px solid #dee2e6;">
                <tr class="text-center">
                    <th style="font-weight: bold; font-size: 16px;">번호</th>
                    <th style="font-weight: bold; font-size: 16px;">제목</th>
                    <th style="font-weight: bold; font-size: 16px;">분류</th>
                    <th style="font-weight: bold; font-size: 16px;">응시조건</th>
                    <th style="font-weight: bold; font-size: 16px;">수료여부</th>

                </tr>

                {% if q %}
                {% else %}
                {% if notice_fixed %}
                {% for notice in notice_fixed %}
                <tr class="table-secondary text-center" style="font-weight: bold; cursor:pointer;" onclick="location.href='/notice/{{ notice.id }}/'">
                    <td style="font-weight: 500;">{{ forloop.counter }} </td>
                    <td class="text-left" style="width:50%"><a id="edu-{{ notice.id }}"><i class="fas fa-bullhorn"></i>&nbsp;&nbsp;&nbsp;{{ notice.title|truncatechars:30 }}</a></td>
                    <td>{{ notice.writer }}</td>
                    <td>{{ notice.registered_date|date:'Y. m. d' }}</td>
                    <td>{{ notice.hits }}</td>
                </tr>
                {% endfor %}
                {% endif %}
                {% endif %}
            </thead>
            <tbody>
                {% if exam_list %}
                    {% for exam in exam_list %}
                        {% if exam.cert == False %}
                            {% if exam.study_cert == False %}
                            <tr class="text-center" style="cursor:pointer;" onclick="alert('응시조건 안맞음. 교육시간20분 이상')">
                                <td style="font-weight: 500;">{{ forloop.counter }} </td>
                                <td class="text-left" style="width:50%; font-weight: 600;"><a id="exam-{{ exam.id }}">{{ exam.quiz_title|truncatechars:30 }}</a></td>
                                <td style="font-weight: 500;">{{ exam.category }}</td>
                                <td style="font-weight: 500;">X</td>
                                <td style="font-weight: 500;">X</td>
                            {% else %}
                            <tr class="text-center" style="cursor:pointer;" onclick="location.href='/exam/{{ exam.product.id }}/'">
                                <td style="font-weight: 500;">{{ forloop.counter }} </td>
                                <td class="text-left" style="width:50%; font-weight: 600;"><a id="exam-{{ exam.id }}">{{ exam.quiz_title|truncatechars:30 }}</a></td>
                                <td style="font-weight: 500;">{{ exam.category }}</td>
                                <td style="font-weight: 500;">O</td>
                                <td style="font-weight: 500;">X</td>
                            {% endif %}
                        </tr>
                        {% else %}
                        <tr class="text-center" style="cursor:pointer;" onclick="alert('수료하셨습니다.')">
                            <td style="font-weight: 500;">{{ forloop.counter }} </td>
                            <td class="text-left" style="width:50%; font-weight: 600;"><a id="exam-{{ exam.id }}">{{ exam.quiz_title|truncatechars:30 }}</a></td>
                            <td style="font-weight: 500;">{{ exam.category }}</td>
                            <td style="font-weight: 500;">O</td>
                            <td style="font-weight: 500;">O</td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    {% if q %}
                    <tr class="text-center">
                        <td style="font-weight: bold; color:gray;" colspan="5">
                            <i class="fas fa-info-circle"></i>&nbsp;일치하는 검색 결과가 없습니다.
                        </td>
                    </tr>
                    {% else %}
                        <tr class="text-center">
                            <td style="font-weight: bold; color:gray;" colspan="5">
                                <i class="fas fa-info-circle"></i>&nbsp;작성된 게시글이 없습니다.
                            </td>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>
    </div>
    
    <div style="margin-top: 30px;">
        <form action="" method="GET">
            <div class="col">
                <div style="float: right;" class="form-row">
                    <div class="form-row">
                        <div class="col" style="margin-top: 10px;">
                            <select style="width: 6em;" class="custom-select custom-select-md" name="type">
                                <option value="all">전체</option>
                                <option value="title">제목</option>
                                <option value="catagory">분류</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col">
                            <!-- <button class="btn btn-md btn-outline-dark" type="submit">검색</button> -->
                            <button class="btn btn-sm" type="submit" id="search_btn">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% if request.user.level == '0' or request.user.level == '1' %}
        <div>
            <div>
                <a href="{% url 'exam:exam_write' %}" id="write_btn" class="btn btn-sm">시험생성</a>
            </div>
            <div>
                <a href="{% url 'exam:quiz_write' %}" id="write_btn" class="btn btn-sm">문제생성</a>
            </div>
        </div>
        <br>
        {% else %}
        <br><br><br>
        {% endif %}
        <div class="col-md-offset-6">
            {% if is_paginated %}
            <!-- <ul class="pagination justify-content-center pagination-sm"> -->
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                        tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}" style="font-size: 15px;">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                        href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}" style="font-size: 15px;">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="font-size: 15px;">다음</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">
    target = window.location.search.split('&')[0].split('=')[1]
    var type = document.getElementsByTagName('option')
    for (var i = 0; i < 5; i++) {
        if (type[i].value === target) {
            type[i].setAttribute('selected', 'selected')
        }
    }
</script>
{% endblock %}

templates/exam/exam_result.html
{% extends "users/main_base.html" %}
{% load static %}
{% block contents %}
<br><br><br>
{{ certificated }}
{{ score }}

{% endblock %}

templates/exam/exam_write.html
{% extends "users/main_base.html" %}
{% load humanize %}
{% load static %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block summernote %}
<!-- <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote-bs4.min.js"></script> -->

<link rel="stylesheet" href="{% static 'css/summernote/summernote.css' %}" type="text/css">
<script src="{% static 'js/summernote/summernote.js' %}"></script>
<!-- <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-lite.min.css" rel="stylesheet"> -->
<!-- <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.16/dist/summernote-lite.min.js"></script> -->

<script type="text/javascript" src="/static/js/lang/summernote-ko-KR.js"></script>
<script>
    $(document).ready(function () {
        $('#id_content').summernote({
            placeholder: '내용을 입력해주세요.',
            height: 500,
            minHeight: 500,
            maxHeight: 500,
            lang: 'ko-KR',
           
            toolbar: [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'help']]
            ]
        });
        $('p').css('margin-bottom','0')
        $('.note-resizebar').css('display','none');
    });
</script>
<!-- CheckBoxCSS -->
<link rel="stylesheet" href="{% static 'css/users/checkbox.css' %}" type="text/css"> 
{% endblock %}

{% block contents %}
{% load static %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">시험과목</h4>
        </div>
    </div>

    <div class="row-mt-5">
        <!--본문-->
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header" style="padding: 0rem 0.8rem">
                    <div class="md-form form-group" style="margin-top: 8.5px;">
                        <div style="padding: 0 5.5px;">
                            <!-- <label for="form_title" class="control-label">{{ form.title.label }}</label> -->
                            시험제목 : {{ QuizContentForm.quiz_title }}
                        </div>
                        <div>
                            분류 : {{ QuizContentForm.category }}
                        </div>
                        <div>
                            교육 : {{ QuizContentForm.product }}
                        </div>
                    </div>
                </div>


            </div>
            
            <div class="text-right" style="margin-top: 10px;">

                {% if edit %}
                <button type="submit" id="write" class="btn btn-sm">{{ edit }}</button>
                {% else %}
                <button type="submit" id="write" class="btn btn-sm" onclick="get_tile_category()">작성하기</button>
                {% endif %}
                <input type="checkbox" id="fileChangeCheck" name="fileChange" style="display: none;">
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $("#write").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    });


</script>

{% if filename %}
<script type = "text/javascript">
    $('[href="{{ file_url }}"]').html("{{ filename }}");
    $('#upload_files-clear_id').css({opacity:'100', position:'relative', 'pointer-events':'auto'})

    $("#id_upload_files").change(function() {
        if ($('#id_upload_files').get(0).files.length == 1) {
            $(".col-sm-12").contents().get(0).nodeValue = '[첨부파일 변경 시 기존 파일은 삭제됩니다.]'
            $('#upload_files-clear_id').attr("checked", false)
            $('#upload_files-clear_id').prev().hide()
            $('#upload_files-clear_id').next().hide()
            $('#upload_files-clear_id').hide()
        }
    });

    $('#upload_files-clear_id').on('click', function(){
        if($(this).prop('checked')){
            $('#id_upload_files').hide()
            document.getElementById('id_upload_files').previousSibling.nodeValue = '[업로드 된 첨부파일을 삭제합니다.]'
        } else{
            $('#id_upload_files').show()
            document.getElementById('id_upload_files').previousSibling.nodeValue = '변경: '
        }
    });

    $('#write').click( function() {
        if($('#id_upload_files').get(0).files.length == 1){
            $('#fileChangeCheck').attr("checked",true)
        }
    });
</script>
{% endif %}

{% endblock %}

templates/exam/result.html
{% extends "users/main_base.html" %}
 
{% block content %}
<div class="container ">
        
    <div class="card-columns" style="padding: 10px; margin: 20px;">
        <div class="card" align="centre " style="width: 32rem; border:5px black solid">
            <img class="card-img-top" src="http://kmit.in/emagazine/wp-content/uploads/2018/02/karnataka-results.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Score: {{score}}</h5>
 
                <p class="card-text">Percentage: {{percent}}%</p>
                <p class="card-text">Time Taken: {{time}} seconds</p>
                <p class="card-text">Correct answers: {{correct}}</p>
                <p class="card-text">Incorrect answers: {{wrong}}</p>
                <p class="card-text">Total questions: {{total}}</p>
                <h5>All the best for next quiz!</h5>
            </div>
        </div>
    </div>
 
</div>
 
{% endblock %}