edu/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'edu'

urlpatterns = [
    path('', views.EduListView.as_view(), name='edu_list'),
    path('study_list/', views.StudyListView.as_view(), name='study_list'),
    # path('pdf', views.pdf_view, name='pdf'),
    path('write/', views.edu_write_view, name='edu_write'),
    path('<int:pk>/', views.edu_detail_view, name='edu_detail'),
    path('<int:pk>/edit/', views.edu_edit_view, name='edu_edit'),
    path('<int:pk>/delete/', views.edu_delete_view, name='edu_delete'),
    path('<int:pk>/savetime/', views.saveTime, name='edu_save'),
    path('download/<int:pk>', views.edu_download_view, name="edu_download"),

    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zzz/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('edu/', include('edu.urls')),
    path('cert/', include('cert.urls')),
    path('exam/', include('exam.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

edu/models.py
import os
from django.db import models
from django.conf import settings
from django.db.models.deletion import SET_NULL
from django.utils import timezone
from uuid import uuid4
from datetime import datetime


from users.choice import *
"""
교육
날짜
카테고리
제목
내용
동영상
"""

def get_file_path(instance, filename):
    ymd_path = datetime.now().strftime('%Y/%m/%d')
    uuid_name = uuid4().hex
    return ''.join(['upload_file/edu/', ymd_path, uuid_name])

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True, verbose_name='상품명')
    description = models.TextField(blank=True, verbose_name='설명')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=128)
    price = models.IntegerField()
    upload_files = models.FileField(upload_to='product/', null=True, blank=True, verbose_name='파일')
    image = models.ImageField(upload_to="product/", null=True, blank=True, verbose_name='이미지')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='등록시간')
    updated_date = models.DateTimeField(auto_now=True, verbose_name="업데이트")


    class Meta:
        ordering = ('name', )
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self) -> str:
        return f'{self.name}'


    def delete(self, *args, **kargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Product, self).delete(*args, **kargs)

    


class Videos(models.Model):
    title = models.CharField(max_length=100)
    video = models.FileField(upload_to='videos/')
        
    def __str__(self):
        return self.title
        
    class Meta:
        verbose_name = 'video'
        verbose_name_plural = 'videos'

edu/forms.py
from django import forms
from .models import Product

class ProductWriteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductWriteForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = '상품명'
        self.fields['name'].widget.attrs.update({
            'placeholder': '상품명을 입력해주세요.',
            'class': 'form-control',
            'id': 'form_title',
            'autofocus': True,
        })

    class Meta:
        model = Product
        fields = ['name', 'category', 'price', 'description', 'upload_files', 'image']

edu/views.py
import re
import urllib
import os
import mimetypes
import natsort
import json
import datetime

from django.conf import settings
from django.views.generic import ListView
from users.decorators import login_message_required, admin_required
from django.shortcuts import render, get_object_or_404, redirect
from django.shortcuts import redirect
from django.http import HttpResponse, Http404, request, response

# Search
from django.contrib import messages
from django.db.models import Q

from .forms import ProductWriteForm
from .models import Product, Videos
from users.models import User
from users.decorators import admin_required
from users.choice import CATEGORY_CHOICES

from payment.models import PurchasedItem

#show pdf
import fitz

class EduListView(ListView):
    model = Product
    paginate_by = 10
    template_name = 'edu/edu_list.html'  #DEFAULT : <app_label>/<model_name>_list.html
    context_object_name = 'notice_list'        #DEFAULT : <model_name>_list html name
    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        notice_list = Product.objects.order_by('id') 
        if search_keyword :
            if len(search_keyword) > 1 :
                if search_type == 'all':
                    search_notice_list = notice_list.filter(Q (name__icontains=search_keyword) | Q (category__icontains=search_keyword))
                elif search_type == 'title':
                    search_notice_list = notice_list.filter(name__icontains=search_keyword)    
                elif search_type == 'catagory':
                    search_notice_list = notice_list.filter(category__icontains=search_keyword)    
                return search_notice_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return notice_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1 :
            context['q'] = search_keyword
        context['type'] = search_type

        return context



# 교육자료 게시글 보기
@login_message_required
def edu_detail_view(request, pk):
    notice = get_object_or_404(Product, pk=pk)
    path_dir = f"{settings.STATICFILES_DIRS[0]}/img/{notice.name}"
    imgs = []
    if notice.upload_files:
        filepath = settings.MEDIA_ROOT + "/" + str(notice.upload_files)
        doc = fitz.open(filepath)
        if os.path.isdir(path_dir):
            imgs = os.listdir(path_dir)
        else:
            os.mkdir(path_dir)
            for idx, pg in enumerate(doc):
                pix = pg.getPixmap()
                output = f"{path_dir}/outfile_{idx}.png"
                pix.writePNG(output)
        imgs = os.listdir(path_dir)
        imgs = [f"{notice.name}/{i}" for i in imgs]
        imgs = natsort.natsorted(imgs)
        
        context = {
            'notice': notice,
            'imgList': imgs,
            'page1':imgs[0],
        }
        return render(request, 'edu/edu_detail.html', context)

# 글쓰기
@login_message_required
@admin_required
def edu_write_view(request):
    if request.method == "POST":
        form = ProductWriteForm(request.POST)
        
        if form.is_valid():
            product = form.save(commit = False)
            if request.FILES:
                try:
                    if 'upload_files' in request.FILES.keys():
                        product.filename = request.FILES['upload_files'].name
                        product.upload_files = request.FILES['upload_files']
                        product.image = request.FILES['image']
                except:
                    print("err")
            product.save()
            return redirect('edu:edu_list')
    else:
        form = ProductWriteForm()

    return render(request, "edu/edu_write.html", {'form': form})

# 수정
@admin_required
def edu_edit_view(request, pk):
    notice = Product.objects.get(id=pk)
    
    if request.method == "POST":
        if(request.user.level == '0'):
            form = ProductWriteForm(request.POST, instance=notice)
            if form.is_valid():
                notice = form.save(commit = False)
                notice.save()
                messages.success(request, "수정되었습니다.")
                return redirect('/edu/'+str(pk))
    else:
        notice = Product.objects.get(id=pk)
        if request.user.level == '0':
            form = ProductWriteForm(instance=notice)
            context = {
                'form': form,
                'edit': '수정하기',
            }
            return render(request, "edu/edu_write.html", context)
        else:
            return redirect('/edu/'+str(pk))


# 삭제

@admin_required
def edu_delete_view(request, pk):
    notice = Product.objects.get(id=pk)
    if request.user.level == '0':
        notice.delete()
        messages.success(request, "삭제되었습니다.")
        return redirect('/edu/')
    else:
        return redirect('/edu/'+str(pk))


@login_message_required
def edu_download_view(request, pk):
    notice = get_object_or_404(Product, pk=pk)
    url = notice.upload_files.url[1:]
    file_url = urllib.parse.unquote(url)
    
    if os.path.exists(file_url):
        with open(file_url, 'rb') as fh:
            quote_file_url = urllib.parse.quote(notice.filename.encode('utf-8'))
            response = HttpResponse(fh.read(), content_type=mimetypes.guess_type(file_url)[0])
            response['Content-Disposition'] = 'attachment;filename*=UTF-8\'\'%s' % quote_file_url
            return response
        raise Http404



class StudyListView(ListView):
    model = PurchasedItem
    products = Product
    paginate_by = 10
    template_name = 'edu/study_list.html'  #DEFAULT : <app_label>/<model_name>_list.html
    context_object_name = 'study_list'        #DEFAULT : <model_name>_list html name
    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        try:
            study_list = PurchasedItem.objects.filter(user=self.request.user)
        except:
            study_list = []

        if search_keyword :
            if len(search_keyword) > 1 :
                if search_type == 'all':
                    search_notice_list = study_list.filter(Q (title__icontains=search_keyword) | Q (content__icontains=search_keyword) | Q (writer__user_id__icontains=search_keyword))
                elif search_type == 'title':
                    search_notice_list = study_list.filter(title__icontains=search_keyword)    
                elif search_type == 'catagory':
                    search_notice_list = study_list.filter(catagory__icontains=search_keyword)    
                return search_notice_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return study_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1 :
            context['q'] = search_keyword
        context['type'] = search_type

        return context

@login_message_required
def saveTime(request, pk):
    products = Product.objects.get(id=pk)
    if request.is_ajax():
        times = request.POST.get('times')
        times = json.loads(times)
        page_num = request.POST.get('current_page')
        item = PurchasedItem.objects.get(user=request.user, product=products)
   
        if item.stayedTime == {}: 
            item.stayedTime = times
            item.save()
        else:
            mysum = datetime.timedelta()
            exist_time = item.stayedTime[page_num]
            new_time = times[page_num]
            (h1, m1, s1) = exist_time.split(':')
            (h2, m2, s2) = new_time.split(':')

            d1 = datetime.timedelta(hours=int(h1), minutes=int(m1), seconds=int(s1))
            d2 = datetime.timedelta(hours=int(h2), minutes=int(m2), seconds=int(s2))

            total = d1 + d2
            mysum += total
            item.stayedTime[page_num] = str(mysum)
            item.save()

        total_time = datetime.timedelta()
        for page in item.stayedTime:
            (h2, m2, s2) = item.stayedTime[page].split(':')
            d2 = datetime.timedelta(hours=int(h2), minutes=int(m2), seconds=int(s2))
            total_time += d2
        item.total_time = total_time
        item.save()

        context = {
            'total_time' : str(item.total_time),
        }
        return HttpResponse(json.dumps(context), content_type="application/json")

templates/edu/edu_detail.html
{% extends "users/main_base.html" %}
{% load static %}

{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}

<br><br><br>

<div class="container">
    <button class="sl-prev" onclick="prev_page()"> < </button>
    <button class="sl-next" onclick="next_page()"> > </button>
    {% if imgList %}
    {% for img in imgList %}
        <input type="hidden" class="myVar" name="imgList" value="/static/img/{{ img }}">
    {% endfor %}
    {% endif %}
    <div class="row-mt-5">
        <div class="col-12">
            <!--본문-->
            <div class="card" style="width: 100%;">
                <!--제목,분류,작성일-->
                <div class="card-header">
                    <strong style="font-size: 18px;">{{ notice.name }}</strong>&nbsp;&nbsp;<span style="font-size: 18px; color: gray;"></span>
                    <span id="study_total"></span>
                    <span style="float:right;">{{ notice.registered_date|date:'Y.m.d. H:i' }}</span>
                </div>
                <div class="card-body" style="min-height: 400px; color:black;">
                    <!--작성자, 조회수-->
                    <div>
                        <!-- <span><i class="fas fa-user-edit"></i>&nbsp;작성자 : {{ notice.writer }}</span> -->
                    </div>
                    <hr>
                    {% if notice.upload_files %}
                    <div class="col-12 text-right">
                        <span style="color: gray;">첨부파일 :&nbsp;</span>
                        <a id="id_uploaded_file" href="{% url 'edu:edu_download' notice.id %}" >{{ notice.filename|truncatechars:25 }}</a>
                    </div>
                    {% endif %}
                    <!--내용-->

                    <div id="img_viewer">
                        <div id="stayed">
                            
                        </div>
                        <p class="pdf">
                            <input type="hidden", id="page_num", value="0">
                            <img id='img_content' src="/static/img/{{ page1 }}">
                        </p>
                    </div>
                </div>
            </div>
            <br>
            <div class="text-right" style="margin-top:-15px;">
                {% if request.user.level == '0' %}
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/edu/{{ notice.id }}/edit/'">수정</button>
                <button class="btn btn-sm" id="detail_btn" data-toggle="modal" data-target="#delete_modal">삭제</button>
                <button class="btn btn-sm" id="detail_btn" data-toggle="modal" data-target="#exam_modal">시험보기</button>
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/edu/'">목록으로</button>
                {% else %}
                <button class="btn btn-sm" id="detail_btn" data-toggle="modal" data-target="#exam_modal">시험보기</button>
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/edu/'">목록으로</button>
                {% endif %}
            </div>
        </div>
    </div>

    <div id="delete_modal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">삭제경고</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>게시글을 삭제하시겠습니까?</p>
                </div>
                <div class="modal-footer">
                    <button onclick=delete_modal(); type="button" class="btn btn-dark">삭제하기</button>
                    <button type="button" class="btn btn-light" data-dismiss="modal">취소하기</button>
                </div>
            </div>
        </div>
    </div>
</div>

<button class="btn btn-sm" id="exam_btn" data-toggle="modal" data-target="#exam_modal" style="visibility: hidden;">시험응시</button>

<div id="exam_modal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">알림창</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {{ total_time }}
            <div class="modal-body">
                <p>시험응시 하시겠습니까?</p>
            </div>
            <div class="modal-footer">
                <button onclick="location.href='/exam/{{ notice.id }}/'" type="button" class="btn btn-dark">시험보기</button>
                <button type="button" class="btn btn-light" data-dismiss="modal">취소하기</button>
            </div>
        </div>
    </div>
</div>

<script>
const today = new Date();
const hours = today.getHours();
const minits = today.getMinutes();
const seconds = today.getSeconds();
let study_total_time = ''
let initial_time = `${hours}:${minits}:${seconds}`;

const stayedGapList = new Object;

const img_list = document.getElementsByName("imgList");
const img = document.getElementById('img_content');
let page_num = parseInt(document.getElementById('page_num').value);

for(let i=0; i < img_list.length + 1; i++){
    stayedGapList[i] = "00:00:00"
}

$(document).ready(function () {
    $('img').css('width', '100%');
});

function delete_modal() {
    location.replace('/edu/{{ notice.id }}/delete/');
}

function prev_page() {
    const prev_page_num = page_num - 1;
    if (prev_page_num < 0){
        alert("첫 번째 페이지 입니다.")
    } else {
        const new_src = img_list[prev_page_num].value
        img.src = new_src
        page_num = prev_page_num
    }
}

function next_page() {
    const next_page_num = page_num + 1;
    if (next_page_num === img_list.length){
        if(timestrToSec(study_total_time) > timestrToSec("00:20:00")){
            const button = document.getElementById('exam_btn');
            button.click();
        }
        else{
            alert("마지막 페이지 입니다. 20분 이상 교육을 수강하지 않았습니다.")
        }

    } else {
        console.log(timestrToSec(study_total_time) > timestrToSec("00:20:00"))
        const new_src = img_list[next_page_num].value
        img.src = new_src
        page_num = next_page_num
    }
}
document.addEventListener('keydown', function(event) {
if(event.keyCode == 37) {
    prev_page();

}
else if(event.keyCode == 39) {
    next_page();
}})


function timestrToSec(timestr) {
    var parts = timestr.split(":");
    return (parts[0] * 3600) +
            (parts[1] * 60) +
            (+parts[2]);
}

function pad(num) {
    if(num < 10) {
        return "0" + num;
    } else {
        return "" + num;
    }
}

function formatTime(seconds) {
    return [pad(Math.floor(seconds/3600)),
            pad(Math.floor(seconds/60)%60),
            pad(seconds%60),
            ].join(":");
}

function drawTime(){
    if(start){
            document.querySelector('div#stayed').innerHTML = `누적시간 : ${start}초`;
    }
}

function timeCheck(){
    const today = new Date();
    const hours = today.getHours();
    const minits = today.getMinutes();
    const seconds = today.getSeconds();
    current = `${hours}:${minits}:${seconds}`;
    stayed = formatTime(timestrToSec(current) - timestrToSec(initial_time));
    initial_time = current

    stayedGapList[page_num] = stayed;

    $.ajax({
        type: "POST",
        headers: {
            'X-CSRFTOKEN' : '{{ csrf_token }}'
        },
        url: "/edu/{{ notice.id }}/savetime/",
        data: {
            times : JSON.stringify(stayedGapList),
            current_page : page_num,
        },
        success: function (data) {
            // console.log(data.total_time)
            study_total_time = data.total_time;
            const study_time = document.getElementById('study_total')
            study_time.innerText = study_total_time
        },
        failure: function () {
            alert("failure");
        }
    });
}

setInterval(timeCheck, 1000);
</script>

{% endblock %}

templates/edu/edu_list.html
{% extends "users/main_base.html" %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">재범방지교육</h4>
            {% if q %}
            <h5 style="color: gray; font-weight: 550;"><i class="fas fa-search"></i>&nbsp;'{{ q }}' 검색 결과입니다.</h5>
            {% endif %}
        </div>
    </div>
    <!-- <div class="category" style="display: inline-flex;">
        <li><a href="">alexis range</a></li>
        <li>a</li>
        <li>a</li>
        <li>a</li>
        <li>a</li>
    </div> -->
    <form action="/cart/add/" method="post">
        {% csrf_token %}
        <div>
            <table class="table table-sm table-hover" id="test">
                <thead style="border-top: 1px solid #dee2e6;">
                    <tr class="text-center">
                        <th style="font-weight: bold; font-size: 16px;">번호</th>
                        <th style="font-weight: bold; font-size: 16px;">교육명</th>
                        <th style="font-weight: bold; font-size: 16px;">분류</th>
                        <th style="font-weight: bold; font-size: 16px;">가격</th>
                        <th style="font-weight: bold; font-size: 16px;">등록일</th>
                        <th style="font-weight: bold; font-size: 16px;">선택</th>
                    </tr>
                </thead>
                <tbody>
                    {% if notice_list %}
                        {% for notice in notice_list %}
                        <tr class="text-center" style="cursor:pointer;" id="edu-{{ notice.id }}" onclick=select(this.id)>
                            <td style="font-weight: 500;">{{ forloop.counter }} </td>
                            {% if request.user.level == '0' or request.user.level == '1' %}
                            <td  class="text-left" style="width:50%; font-weight: 600;" onclick="location.href='/edu/{{ notice.id }}/'"><a id="edu-{{ notice.id }}">{{ notice.name|truncatechars:30 }}</a></td>
                            {% else %}
                            <td  class="text-left" style="width:50%; font-weight: 600;"><a id="edu-{{ notice.id }}">{{ notice.name|truncatechars:30 }}</a></td>
                            {% endif %}
                            <td style="font-weight: 500;">{{ notice.category }}</td>
                            <td style="font-weight: 500;"> &#8361; {{ notice.price }}</td>
                            <td style="font-weight: 500;">{{ notice.registered_date|date:'Y. m. d' }}</td>
                            <td style="font-weight: 500;" onclick="event.cancelBubble = true;"><input id="edu-{{ notice.id }}" type="checkbox" name="selected" value="{{ notice.id }}"></td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        {% if q %}
                        <tr class="text-center">
                            <td style="font-weight: bold; color:gray;" colspan="5">
                                <i class="fas fa-info-circle"></i>&nbsp;일치하는 검색 결과가 없습니다.
                            </td>
                        </tr>
                        {% else %}
                            <tr class="text-center">
                                <td style="font-weight: bold; color:gray;" colspan="5">
                                    <i class="fas fa-info-circle"></i>&nbsp;작성된 게시글이 없습니다.
                                </td>
                            </tr>
                        {% endif %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        {% if request.user.level == '0' or request.user.level == '1' %}
        <div>
            <div>
                <a href="{% url 'edu:edu_write' %}" id="write_btn" class="btn btn-sm">상품작성</a>
                <button class="btn btn-sm" id="detail_btn">담기</button>
            </div>
        </div>
        <br>
        {% else %}
        <div>
            <div>
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/cart/add/'">담기</button>
            </div>
        </div>
        <br>
        {% endif %}
    </form>
    <div style="margin-top: 30px;">
        <form action="" method="GET">
            <div class="col">
                <div style="float: right;" class="form-row">
                    <div class="form-row">

                        <div class="col" style="margin-top: 10px;">
                            <select style="width: 6em;" class="custom-select custom-select-md" name="type">
                                <option value="all">전체</option>
                                <option value="title">상품명</option>
                                <option value="catagory">분류</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col">
                            <button class="btn btn-sm" type="submit" id="search_btn">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <div class="col-md-offset-6">
            {% if is_paginated %}
            <!-- <ul class="pagination justify-content-center pagination-sm"> -->
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                        tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}" style="font-size: 15px;">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                        href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}" style="font-size: 15px;">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="font-size: 15px;">다음</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">

    function select(clicked_id){
        const target = document.getElementById(clicked_id);
        const box = target.getElementsByTagName("input")[0];
        box.click();
    }
</script>
{% endblock %}