cert/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cert'

urlpatterns = [
    path('', views.CertListView.as_view(), name='certification'),
    path('cert_add/', views.cert_add_save, name='cert_add_save'),
    path('<int:pk>/', views.GeneratePDF.as_view(), name='certdownload'),
    # path('<int:pk>/original/', views.get_original, name='certdownload'),
    path('check/', views.CertCheckListView.as_view(), name='cert_check'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

edu/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'edu'

urlpatterns = [
    path('', views.EduListView.as_view(), name='edu_list'),
    path('study_list/', views.StudyListView.as_view(), name='study_list'),
    # path('pdf', views.pdf_view, name='pdf'),
    path('write/', views.edu_write_view, name='edu_write'),
    path('<int:pk>/', views.edu_detail_view, name='edu_detail'),
    path('<int:pk>/edit/', views.edu_edit_view, name='edu_edit'),
    path('<int:pk>/delete/', views.edu_delete_view, name='edu_delete'),
    path('<int:pk>/savetime/', views.saveTime, name='edu_save'),
    path('download/<int:pk>', views.edu_download_view, name="edu_download"),

    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

exam/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'exam'

urlpatterns = [
    path('test/', views.exam_test_view, name='exam_test'),


    path('', views.ExamListView.as_view(), name='exam_list'),
    path('<int:pk>/', views.exam_detail_view, name='exam_detail'),

    path('write/', views.exam_write_view, name='exam_write'),
    path('quiz/', views.quiz_write_view, name='quiz_write'),
    path('<int:pk>/edit/', views.question_write_view, name='question_write'),
    path('<int:pk>/submit/', views.exam_submit_view, name='exam_submit'),




]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('agreement/', views.AgreementView.as_view(), name="agreement"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),

    path('main/', views.main_view, name="main"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name="logout"),

    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),

    path('profile/', views.profile_view, name='profile'),
    path('profile/update/', views.profile_update_view, name='profile_update'),
    path('profile/delete/', views.profile_delete_view, name='profile_delete'),
    path('profile/password/', views.password_edit_view, name='password_edit'),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zzz/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('edu/', include('edu.urls')),
    path('cert/', include('cert.urls')),
    path('exam/', include('exam.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from .choice import *

class UserManager(BaseUserManager):
    def create_user(self, user_id, password, email, hp, name, sex, age, auth, **extra_fields):
        user = self.model(
            user_id = user_id,
            email = email,
            hp = hp,
            name = name,
            sex = sex,
            age = age,
            auth = auth,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, password, email=None, hp=None, name=None, sex=None, age=None, auth=None):
        user = self.create_user(user_id, password, email, hp, name, sex, age, auth)
        user.is_superuser = True
        user.is_staff = True
        user.is_admin = True
        user.level = 0
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    
    objects = UserManager()
    address = models.CharField(max_length=128, verbose_name="주소",null=True, default='')
    user_id = models.CharField(max_length=17, verbose_name="아이디", unique=True)
    password = models.CharField(max_length=256, verbose_name="비밀번호")
    email = models.EmailField(max_length=128, verbose_name="이메일", null=True, unique=True)
    hp = models.IntegerField(verbose_name="핸드폰번호", null=True, unique=True)
    name = models.CharField(max_length=8, verbose_name="이름", null=True)
    sex = models.CharField(choices=GENDER_CHOICES, max_length=8, verbose_name="성별", null=True)
    age = models.CharField(choices=AGE_CHOICES, max_length=18, verbose_name="나이", null=True)
    level = models.CharField(choices=LEVEL_CHOICES, max_length=18, verbose_name="등급", default=3)
    auth = models.CharField(max_length=10, verbose_name="인증번호", null=True)
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name='가입일', null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['email']
    
    def __str__(self):
        return self.user_id

    class Meta:
        db_table = "회원목록"
        verbose_name = "사용자"
        verbose_name_plural = "사용자"

users/views.py
import json
from django.core.serializers.json import DjangoJSONEncoder

from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator

from django.views.generic import View
from django.contrib import messages

from django.core.exceptions import PermissionDenied
from django.views.generic import CreateView, View

from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.views.generic import CreateView, FormView, TemplateView

from django.urls import reverse
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ValidationError 

from .forms import *
from .helper import send_mail, email_auth_num
from .decorators import *
from .models import User

from payment.models import PurchasedItem
from edu.models import Product
from exam.models import QuizContents

# from cart.context_processors import counter
# Create your views here.

# Home
def index(request):
    print(request.user)
    return render(request, 'users/index.html')

@method_decorator(logout_message_required, name='dispatch')
class AgreementView(View):
    def get(self, request, *args, **kwargs):
        request.session['agreement'] = False
        return render(request, 'users/agreement.html')

    def post(self, request, *args, **kwarg):
        if request.POST.get('agreement1', False) and request.POST.get('agreement2', False):
            request.session['agreement'] = True
            return redirect('/users/register/')
        else:
            messages.info(request, "약관에 모두 동의해주세요.")
            return render(request, 'users/agreement.html')


class RegisterView(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = RegisterForm

    def get(self, request, *args, **kwargs):
        if not request.session.get('agreement', False):
            raise PermissionDenied
        request.session['agreement'] = False
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        self.request.session['register_auth'] = True
        messages.success(self.request, '회원님의 입력한 Email 주소로 인증 메일이 발송되었습니다. 인증 후 로그인이 가능합니다.')
        return reverse('users:register_success')

    def form_valid(self, form):
        self.object = form.save()
        send_mail(
            '{}님의 회원가입 인증메일 입니다.'.format(self.object.user_id),
            [self.object.email],
            html=render_to_string('users/register_email.html', {
                'user': self.object,
                'uid': urlsafe_base64_encode(force_bytes(self.object.pk)).encode().decode(),
                'domain': self.request.META['HTTP_HOST'],
                'token': default_token_generator.make_token(self.object),
            }),
        )
        return redirect(self.get_success_url())


# 로그인
@method_decorator(logout_message_required, name='dispatch')
class LoginView(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = '/users/main/'

    def form_valid(self, form):
        user_id = form.cleaned_data.get("user_id")
        password = form.cleaned_data.get("password")

        user = authenticate(self.request, username=user_id, password=password)
        print(user)
        if user is not None:
            self.request.session['user_id'] = user_id
            login(self.request, user)

            # Session Maintain Test

            remember_session = self.request.POST.get('remember_session', False)
            if remember_session:
                settings.SESSION_EXPIRE_AT_BROWSER_CLOSE = False

        return super().form_valid(form)


# 로그아웃
def logout_view(request):
    logout(request)
    return redirect('/')


# 메인화면(로그인 후)
@login_message_required
def main_view(request):
    purchaseds = PurchasedItem.objects.filter(user=request.user)
    exams_list = []
    cert_list = []
    for item in purchaseds:
        exam = QuizContents.objects.get(product=item.product)
        if item.certificated == False:
            exams_list.append(exam)
        else:
            cert_list.append(exam)
    
    context = {
        'edu_list' : purchaseds,
        'exam_list' : exams_list,
        'cert_list' : cert_list,
    }
    return render(request, 'users/main.html', context)


def activate(request, uid64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uid64))
        current_user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
        messages.error(request, '메일 인증에 실패했습니다.')
        return redirect('users:login')

    if default_token_generator.check_token(current_user, token):
        current_user.is_active = True
        current_user.save()

        messages.info(request, '메일 인증이 완료 되었습니다. 회원가입을 축하드립니다!')
        return redirect('users:login')

    messages.error(request, '메일 인증에 실패했습니다.')
    return redirect('users:login')

# 회원가입 인증메일 발송 안내 창
def register_success(request):
    if not request.session.get('register_auth', False):
        raise PermissionDenied
    request.session['register_auth'] = False

    return render(request, 'users/register_success.html')



# 아이디찾기
@method_decorator(logout_message_required, name='dispatch')
class RecoveryIdView(View):
    template_name = 'users/recovery_id.html'
    recovery_id = RecoveryIdForm

    def get(self, request):
        if request.method=='GET':
            form_id = self.recovery_id(None)
        return render(request, self.template_name, { 'form_id':form_id, })    

# 비밀번호찾기
@method_decorator(logout_message_required, name='dispatch')
class RecoveryPwView(View):
    template_name = 'users/recovery_pw.html'
    recovery_pw = RecoveryPwForm

    def get(self, request):
        if request.method=='GET':
            form_pw = self.recovery_pw(None)
            return render(request, self.template_name, { 'form_pw':form_pw, })

# 아이디찾기 AJAX 통신
def ajax_find_id_view(request):
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_id = User.objects.get(name=name, email=email)
       
    return HttpResponse(json.dumps({"result_id": result_id.user_id}, cls=DjangoJSONEncoder), content_type = "application/json")



# 비밀번호찾기 AJAX 통신
def ajax_find_pw_view(request):
    user_id = request.POST.get('user_id')
    name = request.POST.get('name')
    email = request.POST.get('email')
    result_pw = User.objects.get(user_id=user_id, name=name, email=email)

    if result_pw:
        auth_num = email_auth_num()
        result_pw.auth = auth_num 
        result_pw.save()

        send_mail(
            '[TEST] 비밀번호 찾기 인증메일입니다.',
            [email],
            html=render_to_string('users/recovery_email.html', {
                'auth_num': auth_num,
            }),
        )
    # print(auth_num)
    return HttpResponse(json.dumps({"result": result_pw.user_id}, cls=DjangoJSONEncoder), content_type = "application/json")


# 비밀번호찾기 인증번호 확인
def auth_confirm_view(request):
    # if request.method=='POST' and 'auth_confirm' in request.POST:
    user_id = request.POST.get('user_id')
    input_auth_num = request.POST.get('input_auth_num')
    user = User.objects.get(user_id=user_id, auth=input_auth_num)
    # login(request, user)
    user.auth = ""
    user.save()
    request.session['auth'] = user.user_id  
    
    return HttpResponse(json.dumps({"result": user.user_id}, cls=DjangoJSONEncoder), content_type = "application/json")

        
# 비밀번호찾기 새비밀번호 등록
@logout_message_required
def auth_pw_reset_view(request):
    if request.method == 'GET':
        if not request.session.get('auth', False):
            raise PermissionDenied

    if request.method == 'POST':
        session_user = request.session['auth']
        current_user = User.objects.get(user_id=session_user)
        # del(request.session['auth'])
        login(request, current_user)

        reset_password_form = CustomSetPasswordForm(request.user, request.POST)
        
        if reset_password_form.is_valid():
            user = reset_password_form.save()
            messages.success(request, "비밀번호 변경완료! 변경된 비밀번호로 로그인하세요.")
            logout(request)
            return redirect('users:login')
        else:
            logout(request)
            request.session['auth'] = session_user
    else:
        reset_password_form = CustomSetPasswordForm(request.user)

    return render(request, 'users/password_reset.html', {'form':reset_password_form})


@login_message_required
def profile_view(request):
    if request.method == 'GET':
        return render(request, 'users/profile.html')


@login_message_required
def profile_update_view(request):
    if request.method == 'POST':
        user_change_form = CustomCsUserChangeForm(request.POST, instance = request.user)

        if user_change_form.is_valid():
            user_change_form.save()
            messages.success(request, '회원정보가 수정되었습니다.')
            return render(request, 'users/profile.html')
    else:
        user_change_form = CustomCsUserChangeForm(instance = request.user)

        return render(request, 'users/profile_update.html', {'user_change_form':user_change_form})


# 회원탈퇴
@login_message_required
def profile_delete_view(request):
    if request.method == 'POST':
        password_form = CheckPasswordForm(request.user, request.POST)
        
        if password_form.is_valid():
            request.user.delete()
            logout(request)
            messages.success(request, "회원탈퇴가 완료되었습니다.")
            return redirect('/')
    else:
        password_form = CheckPasswordForm(request.user)

    return render(request, 'users/profile_delete.html', {'password_form':password_form})

# 비밀번호 수정
@login_message_required
def password_edit_view(request):
    if request.method == 'POST':

templates/users/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>사이트 이름</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'img/logo.ico' %}">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,700" rel="stylesheet"> <!--필수-->
    <link rel="stylesheet" href="{% static 'css/index/bootstrap.min.css' %}"> <!--필수-->
    

    <link rel="stylesheet" href="{% static 'css/index/style.css' %}"> <!--필수-->
    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" /> <!--필수-->
    <script src="{% static 'js/index/script.js' %}"></script>
  </head>
  
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
  
  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    
    
    <div class="site-navbar-wrap">
      <div class="site-navbar-top">
        <div class="container py-3">
          <div class="row align-items-center">
            <div class="col-6">
              <div class="d-flex mr-auto">
                <a href="#" class="d-flex align-items-center mr-4">
                  <span class="icon-envelope mr-2"></span>
                  <span class="d-none d-md-inline-block">이메일</span>
                </a>
                <a href="#" class="d-flex align-items-center mr-auto">
                  <span class="icon-phone mr-2"></span>
                  <span class="d-none d-md-inline-block">전화번호</span>
                </a>
                {% if user.is_authenticated %}
                <a class="login" href='/users/main/'">마이페이지</a>
                <a class="logout" href='/users/logout/'">로그아웃</a>
                {% else %}
                <a class="login" href='/users/login/'">로그인</a>
                <a class="logout" href='/users/agreement/'">회원가입</a>
                {% endif %}
              </div>

            </div>
            <div class="col-6 text-right">
            </div>
          </div>
        </div>
      </div>

      <div class="site-navbar site-navbar-target js-sticky-header">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-2">
              <h1 class="my-0 site-logo"><a href="/"><img class="logo" style="width: 50px; margin-top: 10px;" src="{% static 'img/logo.png' %}" alt=""></a></h1>
            </div>
            <div class="com-name">
              NAME
            </div>
            <div class="col-10">
              <nav class="my-navigation" role="navigation">
                <div class="">
                  <ul class="">
                    <li class="dropdown">
                      <a class="" href="{% url 'cert:certification' %}"  style="font-weight: 600;">문의하기</a>
                      <div class="dropdown-content">
                        <p class="sub-content"><a href="">1:1 문의</a></p>
                        <p class="sub-content"><a href="">Q&A</a></p>
                      </div>
                    </li>
                    <li class="dropdown">
                      <a class="" href="{% url 'cert:certification' %}"  style="font-weight: 600;">강의실</a>
                      <div class="dropdown-content">
                        <p class="sub-content"><a href="{% url 'edu:edu_list' %}">교육수강</a></p>
                        <p class="sub-content"><a href="{% url 'exam:exam_list' %}">시험</a></p>
                        <p class="sub-content"><a href="{% url 'cert:certification' %}">이수증</a></p>

                      </div>
                    </li>
                    <li class="dropdown">
                      <a class="" href="{% url 'edu:edu_list' %}"  style="font-weight: 600;">교육신청</a>
                      <div class="dropdown-content">
                        <p class="sub-content"><a href="{% url 'edu:edu_list' %}">교육과목</a></p>

                      </div>
                    </li>
                    <li class="dropdown">
                      <a class="" href=""  style="font-weight: 600;">교육안내</a>
                      <div class="dropdown-content">
                        <p class="sub-content"><a href="">인사말</a></p>
                        <p class="sub-content"><a href="">이용방법</a></p>
                        <p class="sub-content"><a href="">비용안내</a></p>

                      </div>
                    </li>
                  
                    <li class="dropdown">
                      <a class="" href="{% url 'index' %}"  style="font-weight: 600;">HOME</a>
                    </li>
                  </ul>
                </div>
              </nav>
            </div>
          </div>
        </div>
      </div>




    </div>
  
    <div class="site-blocks-cover overlay" style="background-image: url('/static/img/back2.jpg'); height: 700px;" data-aos="fade" data-stellar-background-ratio="0.5"id="home-section">
    <!-- <img style="object-fit: fill; display: flex; width: 100%; position: absolute;" src="{% static 'img/back.jpg' %}" alt=""> -->

      <div class="container ">
        <div class="row align-items-center text-center justify-content-center">
          <div class="col-md-8">
           
            <h1 class="font-weight-bold">TEST</h1>
            <p class="sub-text mb-4 d-block">TEST 홈페이지</p>

            {% if user.is_authenticated %}
            <button onclick="location.href='/users/main/'">마이페이지</button>
            <button onclick="location.href='/users/logout/'">로그아웃</button>
            {% else %}
            <button onclick="location.href='/edu/'">교육신청</button>
            <button onclick="location.href='/cert/'">수료증 출력</button>
            {% endif %}
          </div>

        <img class="cert_img" src="{% static 'img/cert.jpg' %}" style="width: 25%; margin-left:700px; margin-top:-216px; margin-bottom: -30px; position: absolute;">

        </div>

      </div>

    </div>  
    <!--사이트 소개-->

    <section class="site-section" id="schedule-section">
        <div class="container" style="margin-left: 30px !important;">
          <div class="row mb-5">
            <div class="col-md-7 text-left heading-wrap mb-5">
              <h2 class="mt-0">RE:BORN</h2>
              <!-- <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p> -->
              <p>TEST TEST</p>
            </div>
            
          </div>
        </div>

        <div class="container-fluid">

          <div class="row no-gutters">
            <div class="col-md-6">
              <div class="sched d-block d-lg-flex">
                <div class="bg-image order-2" style="background-image: url('/static/img/index/free.jpg')"></div>
                <div class="text order-1">
                  <h3 style="font-weight: bold;">교육안내</h3>
                  <p style="color: black;">교육</p>

                  <p><a href="/edu/" class="btn btn-primary btn-sm">바로가기</a></p>
                  
                </div>
                
              </div>

              <div class="sched d-block d-lg-flex">
                <div class="bg-image" style="background-image: url('/static/img/index/anonymous.jpg')"></div>
                <div class="text">
                  <h3 style="font-weight: bold;">교육신청</h3>
                  <p style="color: black;">교육</p>

                  <p><a href="/certification/" class="btn btn-primary btn-sm">바로가기</a></p>
                  
                </div>
                
              </div>

            </div>

            <div class="col-md-6">
              <div class="sched d-block d-lg-flex">
                <div class="bg-image order-2" style="background-image: url('/static/img/index/chatbot.jpg')"></div>
                <div class="text order-1">
                  <h3 style="font-weight: bold;">강의실</h3>
                  <p style="color: black;">교육</p>
                  <!-- <p class="sched-time">
                    <span><span class="fa fa-clock-o"></span> 5:30 PM</span> <br>
                    <span><span class="fa fa-calendar"></span> April 22, 2019</span> <br>
                  </p> -->
                  <p><a href="https://pf.kakao.com/"  class="btn btn-primary btn-sm">바로가기</a></p>
                  
                </div>
                
              </div>

              <div class="sched d-block d-lg-flex">
                <div class="bg-image" style="background-image: url('/static/img/index/timetable.jpg')"></div>
                <div class="text">
                  <h3 style="font-weight: bold;">문의사항</h3>
                  <p style="color: black;">교육</p>
                  <!-- <p class="sched-time">
                    <span><span class="fa fa-clock-o"></span> 5:30 PM</span> <br>
                    <span><span class="fa fa-calendar"></span> April 22, 2019</span> <br>
                  </p> -->
                  <p><a href="/payment/" class="btn btn-primary btn-sm">바로가기</a></p>
                  
                </div>
                
              </div>

            </div>
          </div>
        </div>


      
      </div>
    </section>
    <div class="container">
    </div>


    <footer class="site-footer">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <span>#&nbsp;</span>
            <a href="#" ><i class="fab fa-github"></i>&nbsp;Github</a>
            <span>&nbsp;&</span>
            <a href="#" >&nbsp;<i class="fab fa-blogger"></i>&nbsp;NaverBlog</a>
            <span>&nbsp;에서 확인하실 수 있습니다.</span>
            <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with by <a href="https://colorlib.com"  >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
          </div>
          
        </div>
      </div>
    </footer>
  </div>

  <script src="{% static 'js/index/jquery-3.3.1.min.js' %}"></script> <!--필수-->
  <!-- <script src="{% static 'js/index/jquery-ui.js' %}"></script> -->
  <!-- <script src="{% static 'js/index/popper.min.js' %}"></script> -->
  <!-- <script src="{% static 'js/index/bootstrap.min.js' %}"></script> -->
  <script src="{% static 'js/index/owl.carousel.min.js' %}"></script> <!--필수-->
  <!-- <script src="{% static 'js/index/jquery.countdown.min.js' %}"></script> -->
  <!-- <script src="{% static 'js/index/jquery.magnific-popup.min.js' %}"></script> -->
  <!-- <script src="{% static 'js/index/bootstrap-datepicker.min.js' %}"></script> -->
  <script src="{% static 'js/index/aos.js' %}"></script> <!--필수-->
  <script src="{% static 'js/index/jquery.sticky.js' %}"></script> <!--필수-->
  <!-- <script src="{% static 'js/index/jquery.easing.1.3.js' %}"></script> -->
  <!-- <script src="{% static 'js/index/isotope.pkgd.min.js' %}"></script> -->
  
  <!-- <script src="{% static 'js/index/jquery.fancybox.min.js' %}"></script> -->
  <script src="{% static 'js/index/main.js' %}"></script> <!--필수-->

  <script src="{% static 'js/users/browserCheck.js' %}"></script> <!--필수-->


  {% if messages %}
  {% for message in messages %}
  {% if message.tags %}
  <script>
    alert("{{ message.message }}")
  </script>
  {% endif %}
  {% endfor %}
  {% endif %}
  
  </body>
</html>

templates/users/profile.html
<!-- templates/users/profile.html -->
{% extends "users/main_base.html" %}

{% block mobileView %}
<meta name="viewport" content="width=550, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div style="margin-top: 5rem !important;">
        <div class="col-12">

            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header" style="padding-bottom:8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-cog"></i>&nbsp;&nbsp;내 정보</strong>
                    </div>
                    <div class="card-body">
                        <table style="color:black; margin-left:10px;">
                            <tr>
                                <td class="profile_title">아이디</td>
                                {% if user.level == '0'%}
                                <td class="profile_content">{{ user.user_id }}&nbsp;&nbsp;(개발자)</td>
                                {% elif user.level == '1' %}
                                <td class="profile_content">{{ user.user_id }}&nbsp;&nbsp;(관리자)</td>
                                {% else %}
                                <td class="profile_content">{{ user.user_id }}</td>
                                {% endif %}
                            </tr>
                            <tr>
                                <td class="profile_title">이메일</td>
                                <td class="profile_content">{{ user.email }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">이름</td>
                                <td class="profile_content">{{ user.name }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">연락처</td>
                                <td class="profile_content">0{{ user.hp }}</td>
                            </tr>

                        </table>
    
                        <hr>
                        <div style="text-align: center;">
                        <!-- <div style="margin-left: 10px;"> -->
                            <a href="{% url 'users:profile_update' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-edit"></i>&nbsp;내정보수정</a>&nbsp;&middot;&nbsp;
                            <a href="{% url 'users:password_edit' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-lock"></i>&nbsp;비밀번호변경</a>&nbsp;&middot;&nbsp;
                            <a href="{% url 'users:profile_delete' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-slash"></i>&nbsp;회원탈퇴</a> <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}