edu/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'edu'

urlpatterns = [
    path('', views.EduListView.as_view(), name='edu_list'),
    path('study_list/', views.StudyListView.as_view(), name='study_list'),
    # path('pdf', views.pdf_view, name='pdf'),
    path('write/', views.edu_write_view, name='edu_write'),
    path('<int:pk>/', views.edu_detail_view, name='edu_detail'),
    path('<int:pk>/edit/', views.edu_edit_view, name='edu_edit'),
    path('<int:pk>/delete/', views.edu_delete_view, name='edu_delete'),
    path('<int:pk>/savetime/', views.saveTime, name='edu_save'),
    path('download/<int:pk>', views.edu_download_view, name="edu_download"),

    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

payment/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'payment'

urlpatterns = [
    path('payment/', views.payment_view, name='payment'),
    path('payment/cert/', views.payment_cert_view, name='cert_payment'),
    path('kakaoPaySuccess/product/', views.approval, name='payment_success'),
    path('kakaoPaySuccess/cert/', views.approval_cert, name='cert_payment_success'),





] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('agreement/', views.AgreementView.as_view(), name="agreement"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),

    path('main/', views.main_view, name="main"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name="logout"),

    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),

    path('profile/', views.profile_view, name='profile'),
    path('profile/update/', views.profile_update_view, name='profile_update'),
    path('profile/delete/', views.profile_delete_view, name='profile_delete'),
    path('profile/password/', views.password_edit_view, name='password_edit'),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zzz/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('edu/', include('edu.urls')),
    path('cert/', include('cert.urls')),
    path('exam/', include('exam.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls')),

]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models
from edu.models import Product
from django.conf import settings
from django.db.models.deletion import SET_NULL
from users.choice import *
from django.contrib.postgres.fields import JSONField

# Create your models here.
class PurchasedItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=SET_NULL, null=True, verbose_name='구매자')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='상품명')
    registered_date = models.DateTimeField(auto_now_add=True, verbose_name='구매일')
    certificated = models.BooleanField(default=False, verbose_name="수료여부")
    stayedTime = models.JSONField(default=dict, null=True, verbose_name="머문시간")
    total_time = models.CharField(max_length=128, null=True, default='', verbose_name="총머문시간")
    

    class Meta:
        ordering = ('registered_date', )
        verbose_name = 'PurchasedItem'
        verbose_name_plural = 'PurchasedItem'

    def __str__(self) -> str:
        return f'{self.user}'

payment/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib import messages

from edu.models import Product

from .models import PurchasedItem

from cart.models import Cart, CartItem, CertItem
from cart.views import _cart_id
import requests

from users.decorators import *
from .models import PurchasedItem

from django.db.models import Q

# Create your views here.
@login_message_required
def payment_view(request):
    current_full_url = request.build_absolute_uri()
    url_path = request.path
    target_url = current_full_url.replace(url_path, '')
    print(target_url)
    current_user = str(request.user)
    cart = Cart.objects.get(user=_cart_id(request), item_type = "Product")
    cart_items = CartItem.objects.filter(cart=cart, active=True)
    content = {
        'cart' : cart_items,
    }

    if request.method == "POST":
        URL = 'https://kapi.kakao.com/v1/payment/ready'
        headers = {
            "Authorization": "KakaoAK " + "c7d8f589a61b699314201b6e1cc9f8c6",   # 변경불가
            "Content-type": "application/x-www-form-urlencoded;charset=utf-8",  # 변경불가
        }
        if len(cart_items) > 1:
            items = f'{cart_items[0].product.name}외 {len(cart_items)-1}건'
        else:
            items = cart_items[0].product.name

        quantity = [item.quantity for item in cart_items]
        total_amount = [item.product.price for item in cart_items]
        params = {
            "cid": "TC0ONETIME",    # 테스트용 코드
            "partner_order_id": cart.cart_id,     # 주문번호
            "partner_user_id": current_user,    # 유저 아이디
            "item_name": items,        # 구매 물품 이름
            "quantity": sum(quantity),                # 구매 물품 수량
            "total_amount": sum(total_amount),        # 구매 물품 가격
            "tax_free_amount": "0",         # 구매 물품 비과세
            "approval_url": f"{target_url}/payment/kakaoPaySuccess/",
            "cancel_url": f"{target_url}/cart/",
            "fail_url": f"{target_url}/cart/",
        }
        

        res = requests.post(URL, headers=headers, params=params)
        request.session['tid'] = res.json()['tid']      # 결제 승인시 사용할 tid를 세션에 저장
        next_url = res.json()['next_redirect_pc_url']   # 결제 페이지로 넘어갈 url을 저장
        print(request.session['tid'])
        return redirect(next_url)

    return render(request, 'payment/payment.html', content)

@login_message_required
def approval(request):
    current_user = User.objects.get(user_id=request.user)
    cart = Cart.objects.get(user=_cart_id(request), item_type = "Product")
    cart_items = CartItem.objects.filter(cart=cart, active=True)
    for item in cart_items:
        product = Product.objects.get(name=item.product.name)
        print(product)
        try:
            purchased = PurchasedItem.objects.get(user=request.user, product = product)
            purchased.save()
        except PurchasedItem.DoesNotExist:
            purchased = PurchasedItem.objects.create(
                user = request.user,
                product = product,
            )
            purchased.save()

    URL = 'https://kapi.kakao.com/v1/payment/approve'

    headers = {
        "Authorization": "KakaoAK " + "c7d8f589a61b699314201b6e1cc9f8c6",
        "Content-type": "application/x-www-form-urlencoded;charset=utf-8",
    }
    
    params = {
        "cid": "TC0ONETIME",    # 테스트용 코드
        "tid": request.session['tid'],  # 결제 요청시 세션에 저장한 tid
        "partner_order_id": cart.cart_id,     # 주문번호
        "partner_user_id": current_user,    # 유저 아이디
        "pg_token": request.GET.get("pg_token"),     # 쿼리 스트링으로 받은 pg토큰
    }

    res = requests.post(URL, headers=headers, params=params)
    amount = res.json()['amount']['total']
    res = res.json()
    context = {
        'res': res,
        'amount': amount,
    }
    cart.delete()
    return render(request, 'payment/approval.html', context)


@login_message_required
def approval_cert(request):
    current_user = User.objects.get(user_id=request.user)
    cart = Cart.objects.get(user=_cart_id(request), item_type = "Cert")
    cart_items = CertItem.objects.get(cart=cart, active=True)
    product = cart_items.product
    print(product)

    URL = 'https://kapi.kakao.com/v1/payment/approve'

    headers = {
        "Authorization": "KakaoAK " + "c7d8f589a61b699314201b6e1cc9f8c6",
        "Content-type": "application/x-www-form-urlencoded;charset=utf-8",
    }
    
    params = {
        "cid": "TC0ONETIME",    # 테스트용 코드
        "tid": request.session['tid'],  # 결제 요청시 세션에 저장한 tid
        "partner_order_id": cart.cart_id,     # 주문번호
        "partner_user_id": current_user.id,    # 유저 아이디
        "pg_token": request.GET.get("pg_token"),     # 쿼리 스트링으로 받은 pg토큰
    }

    res = requests.post(URL, headers=headers, params=params)
    amount = res.json()['amount']['total']
    res = res.json()
    context = {
        'res': res,
        'amount': amount,
    }
    return render(request, 'payment/approval.html', context)


class PaidListView(ListView):
    model = PurchasedItem
    paginate_by = 10
    template_name = 'payment/paid_list.html'  #DEFAULT : <app_label>/<model_name>_list.html
    context_object_name = 'notice_list'        #DEFAULT : <model_name>_list html name
    def get_queryset(self):
        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')
        notice_list = PurchasedItem.objects.order_by('id') 
        if search_keyword :
            if len(search_keyword) > 1 :
                if search_type == 'all':
                    search_notice_list = notice_list.filter(Q (title__icontains=search_keyword) | Q (content__icontains=search_keyword) | Q (writer__user_id__icontains=search_keyword))
                elif search_type == 'title':
                    search_notice_list = notice_list.filter(title__icontains=search_keyword)    
                elif search_type == 'catagory':
                    search_notice_list = notice_list.filter(catagory__icontains=search_keyword)    
                return search_notice_list
            else:
                messages.error(self.request, '검색어는 2글자 이상 입력해주세요.')
        return notice_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context['paginator']
        page_numbers_range = 5
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range

        search_keyword = self.request.GET.get('q', '')
        search_type = self.request.GET.get('type', '')

        if len(search_keyword) > 1 :
            context['q'] = search_keyword
        context['type'] = search_type

        return context



@login_message_required
def payment_cert_view(request):
    current_full_url = request.build_absolute_uri()
    url_path = request.path
    target_url = current_full_url.replace(url_path, '')

    current_user = User.objects.get(user_id=request.user)
    cart = Cart.objects.get(user=_cart_id(request), item_type = "Cert")

    cert_items = CertItem.objects.get(cart=cart, active=True)
    content = {
        'cart' : cert_items,
    }

    if request.method == "POST":
        URL = 'https://kapi.kakao.com/v1/payment/ready'
        headers = {
            "Authorization": "KakaoAK " + "c7d8f589a61b699314201b6e1cc9f8c6",   # 변경불가
            "Content-type": "application/x-www-form-urlencoded;charset=utf-8",  # 변경불가
        }

        items = cert_items.cert
        quantity = 1
        total_amount = 30000
        params = {
            "cid": "TC0ONETIME",    # 테스트용 코드
            "partner_order_id": cart.cart_id,     # 주문번호
            "partner_user_id": current_user.id,    # 유저 아이디
            "item_name": items.name,        # 구매 물품 이름
            "quantity": quantity,                # 구매 물품 수량
            "total_amount": total_amount,        # 구매 물품 가격
            "tax_free_amount": "0",         # 구매 물품 비과세
            "approval_url": f"{target_url}/payment/kakaoPaySuccess/cert",
            "cancel_url": f"{target_url}/cart/",
            "fail_url": f"{target_url}/cart/",
        }
        print(params)
        res = requests.post(URL, headers=headers, params=params)
        print(request.session['tid'])
        print(res.json())
        request.session['tid'] = res.json()['tid']      # 결제 승인시 사용할 tid를 세션에 저장
        next_url = res.json()['next_redirect_pc_url']   # 결제 페이지로 넘어갈 url을 저장
        print(request.session['tid'])
        return redirect(next_url)

    return render(request, 'payment/payment.html', content)

templates/payment/approval.html
{% extends "users/main_base.html" %}
{% block contents %}
<br><br><br>
<br><br><br>
<br><br><br>

  <div class="mt-5 pt-5 row justify-content-center">
    <h2 class="text-center my-5 col-12">결제가 완료되었습니다!</h2>
    <div class="col-4 p-5 bg-light">
      <h3 class="text-center my-5">주문자 정보</h3>
      <div>
        <div class="my-3 row"><div class="h5 col-6">주문번호</div><div class="h6 col-6 text-right">{{ res.partner_order_id }}</div></div>
        <div class="my-3 row"><div class="h5 col-6">상품명</div><div class="h6 col-6 text-right">{{ res.item_name }}</div></div>
        <div class="my-3 row"><div class="h5 col-6">결제금액</div><div class="h6 col-6 text-right">{{ amount }}원</div></div>
        <div class="my-3 row"><div class="h5 col-6">결제승인시각</div><div class="h6 col-6 text-right">{{ res.approved_at }}</div></div>
      </div>
      <div class="mt-5 pt-3 text-center">
        <a href="{% url 'users:main' %}" class="btn btn-warning">메인으로 돌아가기</a>
      </div>
    </div>
  </div>
{% endblock %}

templates/payment/paid_list.html
{% extends "users/main_base.html" %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">재범방지교육</h4>
            {% if q %}
            <h5 style="color: gray; font-weight: 550;"><i class="fas fa-search"></i>&nbsp;'{{ q }}' 검색 결과입니다.</h5>
            {% endif %}
        </div>
    </div>
    <form action="/cart/add/" method="post">
        {% csrf_token %}
        <div>
            <table class="table table-sm table-hover">
                <thead style="border-top: 1px solid #dee2e6;">
                    <tr class="text-center">
                        <th style="font-weight: bold; font-size: 16px;">번호</th>
                        <th style="font-weight: bold; font-size: 16px;">교육명</th>
                        <th style="font-weight: bold; font-size: 16px;">분류</th>
                        <th style="font-weight: bold; font-size: 16px;">구매일</th>
                        <th style="font-weight: bold; font-size: 16px;">수료</th>
                    </tr>
                </thead>
                <tbody>
                    {% if notice_list %}
                        {% for notice in notice_list %}
                        <tr class="text-center" style="cursor:pointer;" >
                            <td style="font-weight: 500;">{{ forloop.counter }} </td>
                            <td class="text-left" style="width:50%; font-weight: 600;" onclick="location.href='/edu/{{ notice.id }}/'" ><a id="edu-{{ notice.id }}">{{ notice.name|truncatechars:30 }}</a></td>
                            <td style="font-weight: 500;">{{ notice.category }}</td>
                            <td style="font-weight: 500;"> &#8361; {{ notice.price }}</td>
                            <td style="font-weight: 500;">{{ notice.registered_date|date:'Y. m. d' }}</td>
                            <td style="font-weight: 500;"><input id="selected" type="checkbox" name="selected" value="{{ notice.id }}"></td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        {% if q %}
                        <tr class="text-center">
                            <td style="font-weight: bold; color:gray;" colspan="5">
                                <i class="fas fa-info-circle"></i>&nbsp;일치하는 검색 결과가 없습니다.
                            </td>
                        </tr>
                        {% else %}
                            <tr class="text-center">
                                <td style="font-weight: bold; color:gray;" colspan="5">
                                    <i class="fas fa-info-circle"></i>&nbsp;작성된 게시글이 없습니다.
                                </td>
                            </tr>
                        {% endif %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        {% if request.user.level == '0' or request.user.level == '1' %}
        <div>
            <div>
                <a href="{% url 'edu:edu_write' %}" id="write_btn" class="btn btn-sm">상품작성</a>
                <button class="btn btn-sm" id="detail_btn">담기</button>
            </div>
        </div>
        <br>
        {% else %}
        <div>
            <div>
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/cart/add/'">장바구니 추가</button>
            </div>
        </div>
        <br>
        {% endif %}
    </form>
    <div style="margin-top: 30px;">
        <form action="" method="GET">
            <div class="col">
                <div style="float: right;" class="form-row">
                    <div class="form-row">
                        <div class="col" style="margin-top: 10px;">
                            <select style="width: 6em;" class="custom-select custom-select-md" name="type">
                                <option value="all">전체</option>
                                <option value="title">상품명</option>
                                <option value="catagory">분류</option>
                                <option value="catagory">구매여부</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col">
                            <button class="btn btn-sm" type="submit" id="search_btn">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <div class="col-md-offset-6">
            {% if is_paginated %}
            <!-- <ul class="pagination justify-content-center pagination-sm"> -->
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                        tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}" style="font-size: 15px;">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                        href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}" style="font-size: 15px;">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="font-size: 15px;">다음</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">
    target = window.location.search.split('&')[0].split('=')[1]
    var type = document.getElementsByTagName('option')
    for (var i = 0; i < 5; i++) {
        if (type[i].value === target) {
            type[i].setAttribute('selected', 'selected')
        }
    }
</script>
{% endblock %}

templates/payment/paid_list.html.html
{% extends "users/main_base.html" %}
{% load humanize %}

{% block mobileView %}
<meta name="viewport" content="width=800, user-scalable=yes">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h4 style="font-weight: bold;">재범방지교육</h4>
            {% if q %}
            <h5 style="color: gray; font-weight: 550;"><i class="fas fa-search"></i>&nbsp;'{{ q }}' 검색 결과입니다.</h5>
            {% endif %}
        </div>
    </div>
    <form action="/cart/add/" method="post">
        {% csrf_token %}
        <div>
            <table class="table table-sm table-hover">
                <thead style="border-top: 1px solid #dee2e6;">
                    <tr class="text-center">
                        <th style="font-weight: bold; font-size: 16px;">번호</th>
                        <th style="font-weight: bold; font-size: 16px;">교육명</th>
                        <th style="font-weight: bold; font-size: 16px;">분류</th>
                        <th style="font-weight: bold; font-size: 16px;">구매일</th>
                        <th style="font-weight: bold; font-size: 16px;">수료</th>
                    </tr>
                </thead>
                <tbody>
                    {% if notice_list %}
                        {% for notice in notice_list %}
                        <tr class="text-center" style="cursor:pointer;" >
                            <td style="font-weight: 500;">{{ forloop.counter }} </td>
                            <td class="text-left" style="width:50%; font-weight: 600;" onclick="location.href='/edu/{{ notice.id }}/'" ><a id="edu-{{ notice.id }}">{{ notice.name|truncatechars:30 }}</a></td>
                            <td style="font-weight: 500;">{{ notice.category }}</td>
                            <td style="font-weight: 500;"> &#8361; {{ notice.price }}</td>
                            <td style="font-weight: 500;">{{ notice.registered_date|date:'Y. m. d' }}</td>
                            <td style="font-weight: 500;"><input id="selected" type="checkbox" name="selected" value="{{ notice.id }}"></td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        {% if q %}
                        <tr class="text-center">
                            <td style="font-weight: bold; color:gray;" colspan="5">
                                <i class="fas fa-info-circle"></i>&nbsp;일치하는 검색 결과가 없습니다.
                            </td>
                        </tr>
                        {% else %}
                            <tr class="text-center">
                                <td style="font-weight: bold; color:gray;" colspan="5">
                                    <i class="fas fa-info-circle"></i>&nbsp;작성된 게시글이 없습니다.
                                </td>
                            </tr>
                        {% endif %}
                    {% endif %}
                </tbody>
            </table>
        </div>
        {% if request.user.level == '0' or request.user.level == '1' %}
        <div>
            <div>
                <a href="{% url 'edu:edu_write' %}" id="write_btn" class="btn btn-sm">상품작성</a>
                <button class="btn btn-sm" id="detail_btn">담기</button>
            </div>
        </div>
        <br>
        {% else %}
        <div>
            <div>
                <button class="btn btn-sm" id="detail_btn" onclick="location.href='/cart/add/'">장바구니 추가</button>
            </div>
        </div>
        <br>
        {% endif %}
    </form>
    <div style="margin-top: 30px;">
        <form action="" method="GET">
            <div class="col">
                <div style="float: right;" class="form-row">
                    <div class="form-row">
                        <div class="col" style="margin-top: 10px;">
                            <select style="width: 6em;" class="custom-select custom-select-md" name="type">
                                <option value="all">전체</option>
                                <option value="title">상품명</option>
                                <option value="catagory">분류</option>
                                <option value="catagory">구매여부</option>
                            </select>
                        </div>
                        <div class="col" style="margin-top: 10px;">
                            <input type="text" name="q" value="{{ q }}" class="form-control form-control-md"
                                style="width: 15em;" placeholder="검색어를 입력해주세요.">
                        </div>
                        <div class="col">
                            <button class="btn btn-sm" type="submit" id="search_btn">검색</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <div class="col-md-offset-6">
            {% if is_paginated %}
            <!-- <ul class="pagination justify-content-center pagination-sm"> -->
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page_obj.previous_page_number }}"
                        tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" style="font-size: 15px;">이전</a>
                </li>
                {% endif %}

                {% for page in page_range %}
                <li class="page-item {% if page == page_obj.number %} activate {% endif %}">
                    <a class="page-link" href="?type={{ type }}&q={{ q }}&page={{ page }}" style="font-size: 15px;">{{ page }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                        href="?type={{ type }}&q={{ q }}&page={{ page_obj.next_page_number }}" style="font-size: 15px;">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" style="font-size: 15px;">다음</a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">
    target = window.location.search.split('&')[0].split('=')[1]
    var type = document.getElementsByTagName('option')
    for (var i = 0; i < 5; i++) {
        if (type[i].value === target) {
            type[i].setAttribute('selected', 'selected')
        }
    }
</script>
{% endblock %}

templates/payment/payment.html
{% extends "users/main_base.html" %}
{% load static %}

{% block contents %}
<br><br><br>
<br><br><br>
<br><br><br>

  <div class="row mt-5">
    <h1 class="col-12 text-center my-5">KAKAO PAY  |  무통장입금</h1>
    
    <form method="post" class="col-12 text-center">
      {% csrf_token %}
      <button class="btn btn-warning">카카오페이로 결제하기</button>
      <button class="btn btn-warning">무통장입금(24시간 소요)</button>
    </form>
  </div>
{% endblock %}